# Generated by Django 3.2.11 on 2022-02-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_name', models.TextField()),
                ('interface_url', models.TextField()),
                ('system_type', models.CharField(max_length=60)),
                ('interface_date', models.DateField()),
                ('interface_json', models.TextField()),
            ],
        ),
    ]
