# Generated by Django 4.0.2 on 2022-02-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysql_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mysql_name', models.TextField()),
                ('mysql_Remark', models.TextField()),
                ('system_type', models.CharField(max_length=60)),
                ('interface_date', models.DateField()),
                ('mysql_statement', models.TextField()),
            ],
        ),
    ]
