# Generated by Django 4.0.2 on 2022-02-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mysql_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Case_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Test_case_name', models.TextField()),
                ('Test_case_url', models.TextField()),
                ('system_type', models.CharField(max_length=60)),
                ('interface_date', models.DateField()),
                ('Test_case_json', models.TextField()),
            ],
        ),
    ]
